baseurl: https://michaelmallari.github.io/
languageCode: en-us
title: GPU-Accelerated AI
theme: hugo-michaelmallari
permalinks:
  post: /:slug/
rssLimit: 7
disableKinds: ["taxonomyTerm"]
publishDir: docs
params:
  author: Michael Mallari
  suffix: MS, MBA
  focus: NVIDIA CUDA Python Expert

# "/Users/michael/Library/Application Support/Hugo/0.89.4/"hugo --gc --minify
# Delete /docs folder
# Push root to GitHub, GitLab, Bitbucket
