baseurl: https://michaelmallari.github.io/
languageCode: en-us
title: Applied Computing
theme: hugo-michaelmallari
permalinks:
  post: /:slug/
rssLimit: 3
disableKinds: ["taxonomyTerm"]
publishDir: docs
params:
  author: Michael Mallari
  suffix: MS, MBA
  focus: AI Educator & Coach

# Delete directories, files from /docs
# "/Users/michael/Library/Application Support/Hugo/0.89.4/"hugo --gc --minify
