baseurl: https://michaelmallari.github.io/
languageCode: en-us
title: Applied Computing, Data, and Analytics
theme: hugo-michaelmallari
permalinks:
  post: /:slug/
rssLimit: 3
publishDir: docs
params:
  author: Michael Mallari
  suffix: MBA, MS Applied Analytics, BS Computer Science
  focus: Chief Data & Analytics Officer With Hybrid Skill-Set

# Delete directories, files from /docs
# "/Users/michael/Library/Application Support/Hugo/0.89.4/"hugo --gc --minify
