baseurl: https://michaelmallari.github.io/
languageCode: en-us
title: Applied Computing
theme: hugo-michaelmallari
permalinks:
  post: /:slug/
rssLimit: 24
disableKinds: ["taxonomyTerm"]
publishDir: docs
params:
  author: Michael Mallari
  suffix: MS, MBA
  focus: AI Educator & Coach

# "/Users/michael/Library/Application Support/Hugo/0.89.4/"hugo --gc --minify
# Delete /docs folder
# Push root to GitHub, GitLab, Bitbucket
